
import { Skill, ExperienceItem, Language, TranslationDictionary, Quest } from './types';

// --- TRANSLATIONS ---

export const TRANSLATIONS: Record<Language, TranslationDictionary> = {
  en: {
    role: '"Software QA Engineer"',
    summary: 'Proactive and detail-oriented Software QA Engineer with 6+ years of experience in manual and automated testing across web and mobile applications.',
    runTests: 'Run Test Suite',
    viewSpecs: 'View Specs',
    experience: 'EXPERIENCE',
    frameworks: 'FRAMEWORKS',
    methodology: 'METHODOLOGY',
    expLabel: '6+ Years',
    testingLabel: 'Web & Mobile Testing',
    agileLabel: 'Agile / Scrum',
    aboutMe: 'About Me',
    education: 'Education & Certifications',
    bachelor: "Bachelor's Degree in Electronics Teaching",
    bachelorDesc: 'Kocaeli University — 2016',
    cs50: 'CS50x: Intro to Computer Science',
    cs50Desc: 'Harvard University (edX) — 2025',
    skillsTitle: 'Test Specifications (Skills)',
    suiteStability: 'Suite Stability',
    lastRun: 'Last Run: PASS',
    deploymentLog: 'deployment_history.log',
    viewProject: 'View Project Details',
    hideDetails: 'Hide Details',
    keyAccomplishments: 'Key Accomplishments',
    impact: 'Impact:',
    contactReq: 'New Ticket: Contact Request',
    reporter: 'Reporter (Name)',
    email: 'Contact Email',
    message: 'Description (Message)',
    submit: 'Submit Ticket',
    sentSuccess: 'Message sent successfully!',
    // Sidebar
    navOverview: 'overview',
    navAbout: 'about_me',
    navSkills: 'skills',
    navHistory: 'work_history',
    navContact: 'contact',
    extDeps: 'External Dependencies',
    serverOnline: 'Server: Online',
    // Terminal
    termReady: 'Ready',
    termHeader: 'Terminal — Local — zsh',
    termPlaceholder: "Type 'help' for commands...",
    // Gamification
    level: 'Player Level',
    activeQuest: 'Active Quest',
    allComplete: 'All quests complete!',
    coverage: 'Coverage',
    badges: 'Badges',
    sysCmds: 'System Commands',
    hintSys: 'Hint System',
    // Overlay
    achUnlocked: 'Unlocked',
    levelUp: 'Level Up',
    questComp: 'Complete',
    clickDismiss: 'Dismiss',
    // RPG
    charSheet: 'CHARACTER_SHEET.md',
    stats: 'Attributes',
    lore: 'Character Lore',
    inventory: 'Inventory',
    equipped: 'Equipped',
    attributes: {
        int: 'Intelligence',
        wis: 'Wisdom',
        cha: 'Charisma',
        dex: 'Dexterity'
    },
    // Game Dashboard
    missionStart: 'INITIALIZE SEQUENCE',
    missionBrief: 'MISSION BRIEFING',
    sysStatus: 'SYSTEM STATUS',
    playerReady: 'PLAYER READY',
    currentObj: 'CURRENT OBJECTIVE',
    // Transmission (Contact)
    commsTitle: 'SECURE UPLINK // TRANSMISSION CONSOLE',
    signalStrength: 'SIGNAL STRENGTH',
    encryption: 'ENCRYPTION: AES-256 [ACTIVE]',
    transmitting: 'TRANSMITTING DATA...',
    sourceId: 'SOURCE_ID (NAME)',
    commFreq: 'COMM_FREQUENCY (EMAIL)',
    dataPayload: 'DATA_PAYLOAD (MESSAGE)',
    initiateUpload: 'INITIATE DATA UPLOAD'
  },
  tr: {
    role: '"Yazılım KG Mühendisi"',
    summary: 'Web ve mobil uygulamalarda manuel ve otomasyon testlerinde 6+ yıl deneyime sahip, proaktif ve detay odaklı Yazılım Kalite Güvence Mühendisi.',
    runTests: 'Testleri Çalıştır',
    viewSpecs: 'Özellikleri Gör',
    experience: 'DENEYİM',
    frameworks: 'ÇATILAR',
    methodology: 'METODOLOJİ',
    expLabel: '6+ Yıl',
    testingLabel: 'Web & Mobil Test',
    agileLabel: 'Agile / Scrum',
    aboutMe: 'Hakkımda',
    education: 'Eğitim & Sertifikalar',
    bachelor: "Elektronik Öğretmenliği Lisans Derecesi",
    bachelorDesc: 'Kocaeli Üniversitesi — 2016',
    cs50: 'CS50x: Bilgisayar Bilimlerine Giriş',
    cs50Desc: 'Harvard Üniversitesi (edX) — 2025',
    skillsTitle: 'Test Spesifikasyonları (Yetenekler)',
    suiteStability: 'Paket Kararlılığı',
    lastRun: 'Son Koşu: BAŞARILI',
    deploymentLog: 'dağıtım_geçmişi.log',
    viewProject: 'Proje Detaylarını Gör',
    hideDetails: 'Detayları Gizle',
    keyAccomplishments: 'Önemli Başarılar',
    impact: 'Etki:',
    contactReq: 'Yeni Bilet: İletişim İsteği',
    reporter: 'Bildiren (İsim)',
    email: 'İletişim E-postası',
    message: 'Açıklama (Mesaj)',
    submit: 'Bileti Gönder',
    sentSuccess: 'Mesaj başarıyla gönderildi!',
    navOverview: 'özet',
    navAbout: 'hakkımda',
    navSkills: 'yetenekler',
    navHistory: 'iş_geçmişi',
    navContact: 'iletişim',
    extDeps: 'Harici Bağımlılıklar',
    serverOnline: 'Sunucu: Çevrimiçi',
    termReady: 'Hazır',
    termHeader: 'Terminal — Yerel — zsh',
    termPlaceholder: "Komutlar için 'help' yazın...",
    level: 'Oyuncu Seviyesi',
    activeQuest: 'Aktif Görev',
    allComplete: 'Tüm görevler tamamlandı!',
    coverage: 'Kapsam',
    badges: 'Rozetler',
    sysCmds: 'Sistem Komutları',
    hintSys: 'İpucu Sistemi',
    achUnlocked: 'Başarım',
    levelUp: 'Seviye Atlandı',
    questComp: 'Tamamlandı',
    clickDismiss: 'Kapat',
    charSheet: 'KARAKTER_KARTI.md',
    stats: 'Nitelikler',
    lore: 'Karakter Hikayesi',
    inventory: 'Envanter',
    equipped: 'Kuşanıldı',
    attributes: {
        int: 'Zeka',
        wis: 'Bilgelik',
        cha: 'Karizma',
        dex: 'Çeviklik'
    },
    missionStart: 'BAŞLAT',
    missionBrief: 'GÖREV ÖZETİ',
    sysStatus: 'SİSTEM DURUMU',
    playerReady: 'OYUNCU HAZIR',
    currentObj: 'MEVCUT HEDEF',
    commsTitle: 'GÜVENLİ BAĞLANTI // İLETİM KONSOLU',
    signalStrength: 'SİNYAL GÜCÜ',
    encryption: 'ŞİFRELEME: AES-256 [AKTİF]',
    transmitting: 'VERİ İLETİLİYOR...',
    sourceId: 'KAYNAK_KİMLİĞİ (İSİM)',
    commFreq: 'İLETİŞİM_FREKANSI (E-POSTA)',
    dataPayload: 'VERİ_YÜKÜ (MESAJ)',
    initiateUpload: 'VERİ YÜKLEMESİNİ BAŞLAT'
  },
  es: {
    role: '"Ingeniero de QA"',
    summary: 'Ingeniero de QA de Software proactivo y detallista con más de 6 años de experiencia en pruebas manuales y automatizadas en aplicaciones web y móviles.',
    runTests: 'Ejecutar Pruebas',
    viewSpecs: 'Ver Specs',
    experience: 'EXPERIENCIA',
    frameworks: 'FRAMEWORKS',
    methodology: 'METODOLOGÍA',
    expLabel: '6+ Años',
    testingLabel: 'Pruebas Web y Móviles',
    agileLabel: 'Agile / Scrum',
    aboutMe: 'Sobre Mí',
    education: 'Educación y Certificaciones',
    bachelor: "Licenciatura en Enseñanza de Electrónica",
    bachelorDesc: 'Universidad de Kocaeli — 2016',
    cs50: 'CS50x: Introducción a la Informática',
    cs50Desc: 'Universidad de Harvard (edX) — 2025',
    skillsTitle: 'Especificaciones de Prueba (Habilidades)',
    suiteStability: 'Estabilidad',
    lastRun: 'Última Ej: ÉXITO',
    deploymentLog: 'historial_despliegue.log',
    viewProject: 'Ver Detalles del Proyecto',
    hideDetails: 'Ocultar Detalles',
    keyAccomplishments: 'Logros Clave',
    impact: 'Impacto:',
    contactReq: 'Nuevo Ticket: Solicitud de Contacto',
    reporter: 'Reportero (Nombre)',
    email: 'Correo de Contacto',
    message: 'Descripción (Mensaje)',
    submit: 'Enviar Ticket',
    sentSuccess: '¡Mensaje enviado con éxito!',
    navOverview: 'resumen',
    navAbout: 'sobre_mi',
    navSkills: 'habilidades',
    navHistory: 'historial_laboral',
    navContact: 'contacto',
    extDeps: 'Dependencias Externas',
    serverOnline: 'Servidor: En Línea',
    termReady: 'Listo',
    termHeader: 'Terminal — Local — zsh',
    termPlaceholder: "Escribe 'help' para comandos...",
    level: 'Nivel de Jugador',
    activeQuest: 'Misión Activa',
    allComplete: '¡Todas las misiones completadas!',
    coverage: 'Cobertura',
    badges: 'Insignias',
    sysCmds: 'Comandos del Sistema',
    hintSys: 'Sistema de Pistas',
    achUnlocked: 'Desbloqueado',
    levelUp: 'Nivel',
    questComp: 'Completa',
    clickDismiss: 'Cerrar',
    charSheet: 'HOJA_DE_PERSONAJE.md',
    stats: 'Atributos',
    lore: 'Historia',
    inventory: 'Inventario',
    equipped: 'Equipado',
    attributes: {
        int: 'Inteligencia',
        wis: 'Sabiduría',
        cha: 'Carisma',
        dex: 'Destreza'
    },
    missionStart: 'INICIAR SECUENCIA',
    missionBrief: 'INFORME DE MISIÓN',
    sysStatus: 'ESTADO DEL SISTEMA',
    playerReady: 'JUGADOR LISTO',
    currentObj: 'OBJETIVO ACTUAL',
    commsTitle: 'ENLACE SEGURO // CONSOLA DE TRANSMISIÓN',
    signalStrength: 'FUERZA DE SEÑAL',
    encryption: 'ENCRIPTACIÓN: AES-256 [ACTIVO]',
    transmitting: 'TRANSMITIENDO DATOS...',
    sourceId: 'ID_FUENTE (NOMBRE)',
    commFreq: 'FRECUENCIA_COM (EMAIL)',
    dataPayload: 'CARGA_DATOS (MENSAJE)',
    initiateUpload: 'INICIAR CARGA DE DATOS'
  },
  zh: {
    role: '"软件QA工程师"',
    summary: '积极主动、注重细节的软件QA工程师，在Web和移动应用的各种手动和自动化测试方面拥有6年以上的经验。',
    runTests: '运行测试套件',
    viewSpecs: '查看规格',
    experience: '经验',
    frameworks: '框架',
    methodology: '方法论',
    expLabel: '6年以上',
    testingLabel: 'Web和移动测试',
    agileLabel: '敏捷 / Scrum',
    aboutMe: '关于我',
    education: '教育与认证',
    bachelor: "电子教学学士学位",
    bachelorDesc: '科贾埃利大学 — 2016',
    cs50: 'CS50x: 计算机科学导论',
    cs50Desc: '哈佛大学 (edX) — 2025',
    skillsTitle: '测试规格 (技能)',
    suiteStability: '套件稳定性',
    lastRun: '上次运行: 通过',
    deploymentLog: 'deployment_history.log',
    viewProject: '查看项目详情',
    hideDetails: '隐藏详情',
    keyAccomplishments: '主要成就',
    impact: '影响:',
    contactReq: '新工单: 联系请求',
    reporter: '报告人 (姓名)',
    email: '联系邮箱',
    message: '描述 (消息)',
    submit: '提交工单',
    sentSuccess: '消息发送成功！',
    navOverview: '概览',
    navAbout: '关于我',
    navSkills: '技能',
    navHistory: '工作历史',
    navContact: '联系',
    extDeps: '外部依赖',
    serverOnline: '服务器: 在线',
    termReady: '就绪',
    termHeader: '终端 — 本地 — zsh',
    termPlaceholder: "输入 'help' 查看命令...",
    level: '玩家等级',
    activeQuest: '当前任务',
    allComplete: '所有任务已完成！',
    coverage: '覆盖率',
    badges: '徽章',
    sysCmds: '系统命令',
    hintSys: '提示系统',
    achUnlocked: '解锁',
    levelUp: '升级',
    questComp: '完成',
    clickDismiss: '关闭',
    charSheet: '角色卡.md',
    stats: '属性',
    lore: '背景故事',
    inventory: '物品栏',
    equipped: '已装备',
    attributes: {
        int: '智力',
        wis: '智慧',
        cha: '魅力',
        dex: '敏捷'
    },
    missionStart: '启动序列',
    missionBrief: '任务简报',
    sysStatus: '系统状态',
    playerReady: '玩家就绪',
    currentObj: '当前目标',
    commsTitle: '安全上行链路 // 传输控制台',
    signalStrength: '信号强度',
    encryption: '加密: AES-256 [激活]',
    transmitting: '正在传输数据...',
    sourceId: '源ID (姓名)',
    commFreq: '通信频率 (邮箱)',
    dataPayload: '数据载荷 (消息)',
    initiateUpload: '启动数据上传'
  },
  hi: {
    role: '"सॉफ्टवेयर QA इंजीनियर"',
    summary: 'वेब और मोबाइल अनुप्रयोगों में मैनुअल और स्वचालित परीक्षण में 6+ वर्षों के अनुभव के साथ सक्रिय और विस्तार-उन्मुख सॉफ्टवेयर QA इंजीनियर।',
    runTests: 'टेस्ट सूट चलाएं',
    viewSpecs: 'स्पेक्स देखें',
    experience: 'अनुभव',
    frameworks: 'फ्रेमवर्क',
    methodology: 'कार्यप्रणाली',
    expLabel: '6+ वर्ष',
    testingLabel: 'वेब और मोबाइल परीक्षण',
    agileLabel: 'एजाइल / स्क्रम',
    aboutMe: 'मेरे बारे में',
    education: 'शिक्षा और प्रमाणन',
    bachelor: "इलेक्ट्रॉनिक्स शिक्षण में स्नातक की डिग्री",
    bachelorDesc: 'कोकेली विश्वविद्यालय — 2016',
    cs50: 'CS50x: कंप्यूटर विज्ञान का परिचय',
    cs50Desc: 'हार्वर्ड विश्वविद्यालय (edX) — 2025',
    skillsTitle: 'परीक्षण विनिर्देश (कौशल)',
    suiteStability: 'स्थिरता',
    lastRun: 'अंतिम रन: पास',
    deploymentLog: 'deployment_history.log',
    viewProject: 'परियोजना विवरण देखें',
    hideDetails: 'विवरण छिपाएं',
    keyAccomplishments: 'प्रमुख उपलब्धियां',
    impact: 'प्रभाव:',
    contactReq: 'नया टिकट: संपर्क अनुरोध',
    reporter: 'रिपोर्टर (नाम)',
    email: 'संपर्क ईमेल',
    message: 'विवरण (संदेश)',
    submit: 'टिकट जमा करें',
    sentSuccess: 'संदेश सफलतापूर्वक भेजा गया!',
    navOverview: 'अवलोकन',
    navAbout: 'मेरे_बारे_में',
    navSkills: 'कौशल',
    navHistory: 'कार्य_इतिहास',
    navContact: 'संपर्क',
    extDeps: 'बाहरी निर्भरता',
    serverOnline: 'सर्वर: ऑनलाइन',
    termReady: 'तैयार',
    termHeader: 'टर्मिनल — लोकल — zsh',
    termPlaceholder: "कमांड के लिए 'help' टाइप करें...",
    level: 'खिलाड़ी स्तर',
    activeQuest: 'सक्रिय खोज',
    allComplete: 'सभी खोज पूरी हो गईं!',
    coverage: 'कवरेज',
    badges: 'बैज',
    sysCmds: 'सिस्टम कमांड',
    hintSys: 'संकेत प्रणाली',
    achUnlocked: 'अनलॉक',
    levelUp: 'लेवल अप',
    questComp: 'पूर्ण',
    clickDismiss: 'बंद करें',
    charSheet: 'चरित्र_पत्र.md',
    stats: 'विशेषताएँ',
    lore: 'कथा',
    inventory: 'इन्वेंटरी',
    equipped: 'सुसज्जित',
    attributes: {
        int: 'बुद्धि',
        wis: 'बुद्धिमत्ता',
        cha: 'करिश्मा',
        dex: 'निपुणता'
    },
    missionStart: 'प्रारंभ अनुक्रम',
    missionBrief: 'मिशन ब्रीफिंग',
    sysStatus: 'सिस्टम स्थिति',
    playerReady: 'खिलाड़ी तैयार',
    currentObj: 'वर्तमान उद्देश्य',
    commsTitle: 'सुरक्षित अपलिंक // ट्रांसमिशन कंसोल',
    signalStrength: 'सिग्नल शक्ति',
    encryption: 'एन्क्रिप्शन: AES-256 [सक्रिय]',
    transmitting: 'डेटा संचारित हो रहा है...',
    sourceId: 'स्रोत आईडी (नाम)',
    commFreq: 'कॉम आवृत्ति (ईमेल)',
    dataPayload: 'डेटा पेलोड (संदेश)',
    initiateUpload: 'डेटा अपलोड शुरू करें'
  },
  ar: {
    role: '"مهندس ضمان الجودة البرمجية"',
    summary: 'مهندس ضمان جودة برمجيات استباقي وموجه نحو التفاصيل مع أكثر من 6 سنوات من الخبرة في الاختبار اليدوي والآلي عبر تطبيقات الويب والهاتف المحمول.',
    runTests: 'تشغيل الاختبارات',
    viewSpecs: 'عرض المواصفات',
    experience: 'الخبرة',
    frameworks: 'أطر العمل',
    methodology: 'المنهجية',
    expLabel: '6+ سنوات',
    testingLabel: 'اختبار الويب والجوال',
    agileLabel: 'أجايل / سكروم',
    aboutMe: 'عني',
    education: 'التعليم والشهادات',
    bachelor: "درجة البكالوريوس في تدريس الإلكترونيات",
    bachelorDesc: 'جامعة كوجالي — 2016',
    cs50: 'CS50x: مقدمة في علوم الكمبيوتر',
    cs50Desc: 'جامعة هارفارد (edX) — 2025',
    skillsTitle: 'مواصفات الاختبار (المهارات)',
    suiteStability: 'الاستقرار',
    lastRun: 'آخر تشغيل: ناجح',
    deploymentLog: 'سجل_تاريخ_النشر.log',
    viewProject: 'عرض تفاصيل المشروع',
    hideDetails: 'إخفاء التفاصيل',
    keyAccomplishments: 'الإنجازات الرئيسية',
    impact: 'تأثير:',
    contactReq: 'تذكرة جديدة: طلب اتصال',
    reporter: 'المبلغ (الاسم)',
    email: 'بريد الاتصال',
    message: 'الوصف (الرسالة)',
    submit: 'إرسال التذكرة',
    sentSuccess: 'تم إرسال الرسالة بنجاح!',
    navOverview: 'نظرة_عامة',
    navAbout: 'عني',
    navSkills: 'مهارات',
    navHistory: 'سجل_العمل',
    navContact: 'اتصال',
    extDeps: 'تبعيات خارجية',
    serverOnline: 'الخادم: متصل',
    termReady: 'جاهز',
    termHeader: 'محطة طرفية — محلي — zsh',
    termPlaceholder: "اكتب 'help' للأوامر...",
    level: 'مستوى اللاعب',
    activeQuest: 'مهمة نشطة',
    allComplete: 'اكتملت جميع المهام!',
    coverage: 'تغطية',
    badges: 'شارات',
    sysCmds: 'أوامر النظام',
    hintSys: 'نظام تلميح',
    achUnlocked: 'فتح',
    levelUp: 'مستوى',
    questComp: 'مكتمل',
    clickDismiss: 'أغلق',
    charSheet: 'ورقة_الشخصية.md',
    stats: 'السمات',
    lore: 'القصة الخلفية',
    inventory: 'المخزون',
    equipped: 'مجهز',
    attributes: {
        int: 'ذكاء',
        wis: 'حكمة',
        cha: 'كاريزما',
        dex: 'براعة'
    },
    missionStart: 'بدء التسلسل',
    missionBrief: 'ملخص المهمة',
    sysStatus: 'حالة النظام',
    playerReady: 'اللاعب جاهز',
    currentObj: 'الهدف الحالي',
    commsTitle: 'وصلة آمنة // وحدة التحكم في الإرسال',
    signalStrength: 'قوة الإشارة',
    encryption: 'تشفير: AES-256 [نشط]',
    transmitting: 'جارٍ إرسال البيانات...',
    sourceId: 'معرف المصدر (الاسم)',
    commFreq: 'تردد الاتصال (البريد الإلكتروني)',
    dataPayload: 'حمولة البيانات (الرسالة)',
    initiateUpload: 'بدء تحميل البيانات'
  }
};

// --- GETTERS FOR DYNAMIC DATA ---

export const getSkills = () => SKILLS; // Skills names usually stay in English/Tech terms

export const SKILLS: Skill[] = [
  // Automation
  { id: 'selenium', name: 'Selenium', level: 95, category: 'automation', icon: 'Bot', isMastered: true },
  { id: 'appium', name: 'Appium', level: 90, category: 'automation', icon: 'Smartphone', isMastered: true },
  { id: 'testinium', name: 'Testinium', level: 85, category: 'automation', icon: 'TestTube', isMastered: false },
  { id: 'browserstack', name: 'Browserstack', level: 85, category: 'automation', icon: 'Globe', isMastered: false },
  
  // Languages & Frameworks
  { id: 'java', name: 'Java', level: 90, category: 'languages', icon: 'Coffee', isMastered: true },
  { id: 'python', name: 'Python', level: 80, category: 'languages', icon: 'FileCode', isMastered: false },
  { id: 'cucumber', name: 'Cucumber', level: 85, category: 'languages', icon: 'Sprout', isMastered: false },
  { id: 'gauge', name: 'Gauge', level: 75, category: 'languages', icon: 'Gauge', isMastered: false },

  // API
  { id: 'postman', name: 'Postman', level: 95, category: 'api', icon: 'Send', isMastered: true },
  { id: 'soapui', name: 'SOAP UI', level: 80, category: 'api', icon: 'FileJson', isMastered: false },
  { id: 'swagger', name: 'Swagger', level: 85, category: 'api', icon: 'BookOpen', isMastered: false },

  // CI/CD & Management
  { id: 'azure', name: 'Azure', level: 85, category: 'devops', icon: 'Cloud', isMastered: false },
  { id: 'jira', name: 'Jira', level: 95, category: 'tracking', icon: 'Trello', isMastered: true },
  { id: 'tfs', name: 'TFS', level: 85, category: 'tracking', icon: 'GitMerge', isMastered: false },
  { id: 'sql', name: 'SQL', level: 80, category: 'languages', icon: 'Database', isMastered: false },
];

export const getExperience = (lang: Language): ExperienceItem[] => {
  const isTr = lang === 'tr';
  // Simplified translation logic for descriptions to keep file size manageable
  // In a real app, every string would be in the dictionary.
  
  return [
    {
      id: 'monster',
      role: 'Software QA Engineer',
      company: 'Monster Notebook',
      period: isTr ? 'Eyl 2021 – Günümüz' : 'Sep 2021 – Present',
      location: isTr ? 'İstanbul, Türkiye' : 'Istanbul, Turkey',
      description: isTr ? [
        'UI, E2E entegrasyon ve API testlerine odaklanan e-ticaret projelerine katkıda bulundu.',
        'Selenium ve Appium (Testinium, Browserstack, Java) kullanarak otomasyon çerçeveleri tasarladı ve uyguladı.',
        'Kullanıcı hikayelerine dayalı kapsamlı Test Planları, Test Senaryoları ve Uçtan Uca Senaryolar oluşturdu ve yürüttü.',
        'Postman kullanarak manuel API testleri gerçekleştirdi ve işbirliği için Azure kullandı.',
        'Sprint planlama, günlük scrumlar ve retrospektifler dahil olmak üzere Agile seremonilerine aktif olarak katıldı.'
      ] : [
        'Contributed to e-commerce projects focusing on UI, E2E integration, and API testing.',
        'Designed and implemented automation frameworks using Selenium and Appium (Testinium, Browserstack, Java).',
        'Created and executed comprehensive Test Plans, Test Cases, and End-to-End Scenarios based on user stories.',
        'Conducted manual API testing using Postman and utilized Azure as a remote repository.',
        'Actively participated in Agile ceremonies: sprint planning, daily scrums, grooming, and retrospectives.'
      ],
      techStack: ['Selenium', 'Appium', 'Java', 'Azure', 'Postman'],
      projects: [
        {
          title: isTr ? "Test Otomasyon Mimarisi" : "Test Automation Architecture",
          desc: isTr ? "Çeşitli platformlar için web ve mobil test otomasyon sistemleri tasarladı ve uyguladı." : "Designed and implemented web and mobile test automation systems for various platforms.",
          impact: isTr ? "Azure uzak deposu kullanılarak işbirliği kolaylaştırıldı." : "Streamlined collaboration using Azure remote repository."
        },
        {
          title: isTr ? "Kritik Proje Testleri" : "Critical Project Testing",
          desc: isTr ? "Kritik sürümler için Regresyon, Entegrasyon ve E2E testleri gerçekleştirdi." : "Performed Regression, Integration, and E2E testing for critical releases.",
          impact: isTr ? "Kaliteyi sağlamak için yazılım hatalarına dair detaylı dokümantasyon hazırladı." : "Authored detailed documentation for software defects to ensure quality."
        }
      ]
    },
    {
      id: 'dogus',
      role: isTr ? 'Software QA Engineer (Takım Lideri)' : 'Software QA Engineer (Team Lead)',
      company: 'Doğuş Technology',
      period: isTr ? 'May 2021 – Eyl 2021' : 'May 2021 – Sep 2021',
      location: isTr ? 'İstanbul, Türkiye' : 'Istanbul, Turkey',
      description: isTr ? [
        '"Zubizu" mobil uygulaması için QA Takım Lideri olarak QA çalışmalarına liderlik etti.',
        'Test ekibini yönetti, stratejiler belirledi ve çözülen hataları denetledi.',
        'Test süreçleri için kapsamlı bir Ana Plan geliştirdi ve yeniden kullanılabilir test senaryosu şablonları oluşturdu.',
        'Azure araçlarını kullanarak görev bağlantılarını ve senaryo güncellemelerini izledi.',
        'Regresyon senaryolarının otomasyon ekibi tarafından otomatikleştirilmesini sağladı.'
      ] : [
        'Led QA efforts for the "Zubizu" mobile application as QA Team Lead.',
        'Managed the test team, established strategies, and supervised resolved bugs.',
        'Developed a comprehensive Master Plan for testing processes and created reusable test case templates.',
        'Monitored task connections and scenario updates using Azure tools.',
        'Ensured regression scenarios were automated by the automation team.'
      ],
      techStack: ['Mobile Testing', 'Azure', 'Test Management', 'Zubizu'],
      projects: [
        {
          title: isTr ? "Zubizu KG Liderliği" : "Zubizu QA Leadership",
          desc: isTr ? "Test ekibini yönetti ve kapsamlı test stratejileri belirledi." : "Managed the test team and established comprehensive testing strategies.",
          impact: isTr ? "Sorunsuz test süreçleri ve kaliteli teslimatlar sağladı." : "Delivered seamless testing processes and quality deliverables."
        },
        {
          title: isTr ? "Süreç Optimizasyonu" : "Process Optimization",
          desc: isTr ? "Test senaryoları için yeniden kullanılabilir şablonlar oluşturdu ve test dokümantasyonunu inceledi." : "Created reusable templates for test cases and reviewed test documentation.",
          impact: isTr ? "İşleme alınabilir test öğeleri ile backlog iyileştirmesini destekledi." : "Supported backlog refinement with actionable test items."
        }
      ]
    },
    {
      id: 'akbank',
      role: 'Software QA Engineer',
      company: 'Akbank via Netaş',
      period: isTr ? 'Eyl 2018 – May 2021' : 'Sep 2018 – May 2021',
      location: isTr ? 'İstanbul, Türkiye' : 'Istanbul, Turkey',
      description: isTr ? [
        'Mobil bankacılık projelerinde uzmanlaştı, UI ve E2E entegrasyon testleri gerçekleştirdi.',
        'Mobil bankacılık uygulamasının ön uç işlevsellik testlerini yürüttü.',
        'Verimli sorun çözümü için TFS kullanarak hataları takip etti ve raporladı.',
        'Kullanıcı Kabul Testleri (UAT) gerçekleştirdi ve işleme alınabilir geri bildirimler hazırladı.',
        'Güçlü arka uç doğrulaması için SOAP UI kullanarak web servis testleri gerçekleştirdi.'
      ] : [
        'Specialized in mobile banking projects, performing UI and E2E integration tests.',
        'Executed front-end functionality tests of the mobile banking app.',
        'Tracked and reported bugs using TFS for efficient issue resolution.',
        'Conducted User Acceptance Tests (UAT) and prepared actionable feedback.',
        'Conducted web service testing using SOAP UI for robust backend validation.'
      ],
      techStack: ['Mobile Banking', 'TFS', 'SOAP UI', 'SQL'],
      projects: [
        {
          title: isTr ? "Mobil Bankacılık Doğrulama" : "Mobile Banking Validation",
          desc: isTr ? "Mobil uygulamalar için manuel ve regresyon testleri gerçekleştirdi ve veri setlerini korudu." : "Performed manual and regression testing for mobile applications and maintained datasets.",
          impact: isTr ? "Akbank mobil uygulamalarında işlevsellik ve kullanılabilirliği sürdürdü." : "Maintained functionality and usability across Akbank mobile apps."
        },
        {
          title: isTr ? "Arka Uç Entegrasyonu" : "Backend Integration",
          desc: isTr ? "Güçlü arka uç doğrulaması için SOAP UI kullanarak web servis testleri gerçekleştirdi." : "Conducted web service testing using SOAP UI for robust backend validation.",
          impact: isTr ? "Analiz belgelerine dayalı test senaryolarını TFS'e entegre etti." : "Integrated test scenarios based on analysis documents into TFS."
        }
      ]
    }
  ];
};

export const getQuests = (t: TranslationDictionary): Quest[] => [
  { id: 'q1', title: 'System Initialization', description: t.runTests + ' to verify system integrity.', target: 1, current: 0, rewardXp: 300, isCompleted: false },
  { id: 'q2', title: 'Bug Hunter', description: 'Find and squash 3 hidden bugs in the UI.', target: 3, current: 0, rewardXp: 500, isCompleted: false },
  { id: 'q3', title: 'Full Coverage', description: 'Navigate to all 5 sections of the portfolio.', target: 5, current: 0, rewardXp: 800, isCompleted: false },
  { id: 'q4', title: 'Grand Master', description: 'Unlock all achievements.', target: 5, current: 0, rewardXp: 1000, isCompleted: false },
];

export const getInitialLogs = (lang: Language): string[] => {
    // Keep logs mostly English for "Tech Realism" but maybe localize the header
    return [
        "Initializing TestSuite.ui v3.0.1...",
        "Loading profile data for Turan Aymis...",
        "Syncing with Azure/TFS Repositories... [MOCKED]",
        "Calibrating automation proficiency...",
        "System ready. Awaiting user input."
    ];
};
